services:
  db:
    image: pgvector/pgvector:pg16
    container_name: fraud_rag_db
    ports:
      - "6024:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fraud_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
